/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.dao.CaixaDAO;
import br.edu.ifsp.pep.dao.SangriaDAO;
import br.edu.ifsp.pep.dao.VendaDAO;
import br.edu.ifsp.pep.model.Caixa;
import br.edu.ifsp.pep.model.StatusCaixa;
import br.edu.ifsp.pep.model.Venda;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Yuri
 */
public class CaixaForm extends javax.swing.JDialog {

    /**
     * Creates new form CaixaForm
     */
    private Caixa caixa;
    
    private List<Venda> vendas = new ArrayList<>();
    
    private VendaDAO vendaDAO = new VendaDAO();
    

    private CaixaDAO caixaDAO = new CaixaDAO();

    public CaixaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bSangria = new javax.swing.JButton();
        bFecharCaixa = new javax.swing.JButton();
        bPagamento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bAbrirCaixa = new javax.swing.JButton();
        lStatus = new javax.swing.JLabel();
        lValorCaixa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa");

        bSangria.setBackground(new java.awt.Color(102, 102, 255));
        bSangria.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bSangria.setForeground(new java.awt.Color(255, 255, 255));
        bSangria.setText("Realizar Sangria");
        bSangria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSangriaActionPerformed(evt);
            }
        });

        bFecharCaixa.setBackground(new java.awt.Color(102, 102, 255));
        bFecharCaixa.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bFecharCaixa.setForeground(new java.awt.Color(255, 255, 255));
        bFecharCaixa.setText("Fechar Caixa");
        bFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharCaixaActionPerformed(evt);
            }
        });

        bPagamento.setBackground(new java.awt.Color(102, 102, 255));
        bPagamento.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bPagamento.setForeground(new java.awt.Color(255, 255, 255));
        bPagamento.setText("Realizar Pagamento");
        bPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagamentoActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Valor no caixa");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Status");

        bAbrirCaixa.setBackground(new java.awt.Color(102, 102, 255));
        bAbrirCaixa.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bAbrirCaixa.setForeground(new java.awt.Color(255, 255, 255));
        bAbrirCaixa.setText("Abrir Caixa");
        bAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirCaixaActionPerformed(evt);
            }
        });

        lStatus.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lStatus.setForeground(new java.awt.Color(102, 102, 255));

        lValorCaixa.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lValorCaixa.setForeground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lValorCaixa)
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAbrirCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bSangria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSangria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lStatus)
                    .addComponent(lValorCaixa))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirCaixaActionPerformed

        CaixaCreateForm caixaCreateForm = new CaixaCreateForm(null, rootPaneCheckingEnabled);

        caixaCreateForm.setVisible(true);

        if (caixaCreateForm.getCaixa() != null) {

            try {

                caixa = caixaCreateForm.getCaixa();
                caixaDAO.inserir(caixa);
                lStatus.setText(String.valueOf(caixa.getSituacao()));
                lValorCaixa.setText(String.valueOf(caixa.getSaldo()));

            } catch (Exception ex) {

                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_bAbrirCaixaActionPerformed

    private void bSangriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSangriaActionPerformed

        if (caixa != null) {

            SangriaCreateForm sangriaCreateForm = new SangriaCreateForm(null, rootPaneCheckingEnabled, caixa);

            sangriaCreateForm.setVisible(true);

            if (sangriaCreateForm.getSangria() != null) {

                try {

                    new SangriaDAO().inserir(sangriaCreateForm.getSangria());
                    caixa.setSaldo(caixa.getSaldo() - sangriaCreateForm.getSangria().getValor());
                    lValorCaixa.setText(String.valueOf(caixa.getSaldo()));

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        } else {

            JOptionPane.showMessageDialog(null, "Abra o caixa",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bSangriaActionPerformed

    private void bFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharCaixaActionPerformed

        if (caixa != null) {

            int resposta = JOptionPane.showConfirmDialog(
                    null, "Confirmar o fechamento do caixa?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {

                try {

                    caixa.setSaida(LocalDateTime.now());
                    caixa.setSaldoFinal(caixa.getSaldo());
                    lValorCaixa.setText(String.valueOf(caixa.getSaldo()));
                    caixa.setSituacao(StatusCaixa.Fechado);

                    caixaDAO.alterar(caixa);

                    this.dispose();

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        } else {

            JOptionPane.showMessageDialog(null, "Abra o caixa",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bFecharCaixaActionPerformed

    private void bPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagamentoActionPerformed
        
        if(caixa != null){
        
        ItemVendaListForm itemVendaListForm = new ItemVendaListForm(null, rootPaneCheckingEnabled, caixa);
        
        itemVendaListForm.setVisible(true);
        
        caixa.setSaldo(caixa.getSaldo() + itemVendaListForm.getSaldo());
        lValorCaixa.setText(String.valueOf(caixa.getSaldo()));
        
        }else {

            JOptionPane.showMessageDialog(null, "Abra o caixa",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaixaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaixaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaixaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaixaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CaixaForm dialog = new CaixaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrirCaixa;
    private javax.swing.JButton bFecharCaixa;
    private javax.swing.JButton bPagamento;
    private javax.swing.JButton bSangria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lValorCaixa;
    // End of variables declaration//GEN-END:variables
}
