/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.dao.CompraDAO;
import br.edu.ifsp.pep.model.Compra;
import br.edu.ifsp.pep.model.CompraProduto;
import br.edu.ifsp.pep.model.Fornecedor;
import br.edu.ifsp.pep.model.Parcela;
import br.edu.ifsp.pep.model.Produto;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuri
 */
public class CompraForm extends javax.swing.JDialog {

    /**
     * Creates new form CompraCreateForm
     */
    private Fornecedor fornecedorSelecionado;

    private Produto produtoSelecionado;

    private final Compra compra = new Compra();

    private final List<CompraProduto> compraprodutos = new ArrayList();

    public CompraForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bPesquisaFornecedor = new javax.swing.JButton();
        jsQuantidade = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        bPesquisaProduto = new javax.swing.JButton();
        bAdicionarCompra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        sParcelas = new javax.swing.JSpinner();
        bCancelar = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        bCadastrar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        tfPesquisaFornecedor = new javax.swing.JTextField();
        tfPesquisaProduto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Compra");

        bPesquisaFornecedor.setBackground(new java.awt.Color(102, 102, 255));
        bPesquisaFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bPesquisaFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        bPesquisaFornecedor.setText("Pesquisar Fornecedor");
        bPesquisaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisaFornecedorActionPerformed(evt);
            }
        });

        jsQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Quantidade");

        bPesquisaProduto.setBackground(new java.awt.Color(102, 102, 255));
        bPesquisaProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bPesquisaProduto.setForeground(new java.awt.Color(255, 255, 255));
        bPesquisaProduto.setText("Pesquisar Produto");
        bPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisaProdutoActionPerformed(evt);
            }
        });

        bAdicionarCompra.setBackground(new java.awt.Color(102, 102, 255));
        bAdicionarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bAdicionarCompra.setForeground(new java.awt.Color(255, 255, 255));
        bAdicionarCompra.setText("Adicionar Compra");
        bAdicionarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarCompraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Produto");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Fornecedor");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Fornecedor", "Valor Unidade", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Parcelas");

        sParcelas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        bCancelar.setBackground(new java.awt.Color(102, 102, 255));
        bCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCancelar.setForeground(new java.awt.Color(255, 255, 255));
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bRemover.setBackground(new java.awt.Color(102, 102, 255));
        bRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bRemover.setForeground(new java.awt.Color(255, 255, 255));
        bRemover.setText("Remover");
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });

        bCadastrar.setBackground(new java.awt.Color(102, 102, 255));
        bCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        bCadastrar.setText("Cadastrar");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });

        tfPesquisaFornecedor.setBorder(null);
        tfPesquisaFornecedor.setEnabled(false);

        tfPesquisaProduto.setBorder(null);
        tfPesquisaProduto.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCadastrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(544, 544, 544))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bPesquisaProduto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jsQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPesquisaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bPesquisaFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bAdicionarCompra))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bPesquisaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(tfPesquisaProduto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPesquisaFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(tfPesquisaFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAdicionarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed

        compra.setCompraProdutos(compraprodutos);
        compra.setDataCompra(LocalDate.now());
        compra.setFornecedor(fornecedorSelecionado);

        double valorTotal = 0;

        for (CompraProduto cp : compraprodutos) {
            valorTotal += cp.getValor();
        }
        compra.setValorTotal(valorTotal);

        List<Parcela> parcelas = new ArrayList<>();
        int quantidadeParcelas = (int) sParcelas.getValue();

        double valorParcela = valorTotal / quantidadeParcelas;
        LocalDate dataVencimento = LocalDate.now();

        for (int i = 1; i <= quantidadeParcelas; i++) {
            dataVencimento = dataVencimento.plusMonths(1);
            parcelas.add(new Parcela(dataVencimento, valorParcela, compra));
        }
        compra.setParcelas(parcelas);

        try {
            new CompraDAO().inserir(compra);
            JOptionPane.showMessageDialog(null, "Compra Registrada.");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Insira um Item",
                "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        int selectedRow = tabela.getSelectedRow();

        if(selectedRow != -1){

            compraprodutos.remove(selectedRow);

            this.atualizarTabela();
        }
        else{

            JOptionPane.showMessageDialog(null, "Selecione uma compra",
                "Atenção", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_bRemoverActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAdicionarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarCompraActionPerformed

        if (this.produtoSelecionado != null) {

            Integer quantidade = (Integer) jsQuantidade.getValue();

            if (quantidade > produtoSelecionado.getQuantidade()) {

                JOptionPane.showMessageDialog(null,
                    "Quantidade invalida", "Alerta",
                    JOptionPane.WARNING_MESSAGE);

            }

            if (this.fornecedorSelecionado != null) {

                CompraProduto compraProduto = pesquisarCompraProduto(produtoSelecionado);

                try {
                    atualizaCompraProduto(compraProduto, produtoSelecionado, quantidade);
                    atualizarTabela();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,
                        ex.getMessage(), "Alerta",
                        JOptionPane.WARNING_MESSAGE);
                }
            } else {

                JOptionPane.showMessageDialog(null,
                    "Selecione um fornecedor", "Alerta",
                    JOptionPane.WARNING_MESSAGE);
            }

        } else {

            JOptionPane.showMessageDialog(null,
                "Selecione um produto", "Alerta",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bAdicionarCompraActionPerformed

    private void bPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisaProdutoActionPerformed

        ProdutoPesquisaForm produtoPesquisaForm = new ProdutoPesquisaForm(null, rootPaneCheckingEnabled);

        produtoPesquisaForm.setVisible(true);

        produtoSelecionado = produtoPesquisaForm.getProdutoSelecionado();

        if (produtoSelecionado != null)
        tfPesquisaProduto.setText(produtoSelecionado.getDescricao());

        else
        tfPesquisaProduto.setText("");
    }//GEN-LAST:event_bPesquisaProdutoActionPerformed

    private void bPesquisaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisaFornecedorActionPerformed

        FornecedorPesquisaForm fornecedorPesquisaForm = new FornecedorPesquisaForm(null, rootPaneCheckingEnabled);

        fornecedorPesquisaForm.setVisible(true);

        fornecedorSelecionado = fornecedorPesquisaForm.getFornecedor();

        if (fornecedorSelecionado != null) {

            tfPesquisaFornecedor.setText(fornecedorSelecionado.getNome());
        } else {

            tfPesquisaFornecedor.setText("");
        }
    }//GEN-LAST:event_bPesquisaFornecedorActionPerformed

    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setNumRows(0);
        for (CompraProduto cp : compraprodutos) {

            model.addRow(new Object[]{
                cp.getProduto(),
                fornecedorSelecionado,
                cp.getProduto().getPreco(),
                cp.getValor()
            });
        }
    }

    private void atualizaCompraProduto(CompraProduto compraProduto, Produto produto, Integer quantidade) throws Exception {
        if (compraProduto == null) {

            compraProduto = new CompraProduto(compra, produto, produto.getPreco() * quantidade, quantidade);
            this.compraprodutos.add(compraProduto);

        } else {

            compraProduto.setQuantidade(quantidade + compraProduto.getQuantidade());
            compraProduto.setValor((quantidade * produto.getPreco()) + compraProduto.getValor());
        }

    }

    private CompraProduto pesquisarCompraProduto(Produto produto) {
        for (CompraProduto cp : compraprodutos) {
            if (cp.getProduto().equals(produto)) {
                return cp;
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CompraForm dialog = new CompraForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdicionarCompra;
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bPesquisaFornecedor;
    private javax.swing.JButton bPesquisaProduto;
    private javax.swing.JButton bRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jsQuantidade;
    private javax.swing.JSpinner sParcelas;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfPesquisaFornecedor;
    private javax.swing.JTextField tfPesquisaProduto;
    // End of variables declaration//GEN-END:variables
}
