package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.model.Funcionario;
import br.edu.ifsp.pep.model.StatusFuncionario;
import br.edu.ifsp.pep.model.TipoFuncionario;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class FuncionarioCreateForm extends javax.swing.JDialog {

    /**
     * Creates new form PessoaCreateForm
     */
    Funcionario funcionario = new Funcionario();

    private boolean isEditar = false;

    public Funcionario getFuncionario() {
        return this.funcionario;
    }

    public void setIsEditar(boolean isEditar) {
        this.isEditar = isEditar;
    }

    public void setFuncionario(Funcionario funcionario) {
        
        this.funcionario.setId(funcionario.getId());
        tfNome.setText(funcionario.getNome());
        tfLogin.setText(funcionario.getLogin());
        pfSenha.setText(funcionario.getSenha());
        tfCpf.setText(funcionario.getCpf());
        tfEmail.setText(funcionario.getEmail());
        tfTelefone.setText(funcionario.getTelefone());

        switch (funcionario.getTipo()) {

            case Gerente:
                rbGerente.setSelected(true);
                break;

            case Atendente:
                rbAtendente.setSelected(true);
                break;

            case Caixa:
                rbCaixa.setSelected(true);
                break;
        }

    }

    public FuncionarioCreateForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBorderGradient1 = new br.ifsp.edu.pep.view.awt.PanelBorderGradient();
        lTitulo1 = new javax.swing.JLabel();
        panelBorderGradient2 = new br.ifsp.edu.pep.view.awt.PanelBorderGradient();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tfCpf = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        panelBorderGradient3 = new br.ifsp.edu.pep.view.awt.PanelBorderGradient();
        panelBorderGradient4 = new br.ifsp.edu.pep.view.awt.PanelBorderGradient();
        jLabel5 = new javax.swing.JLabel();
        rbGerente = new javax.swing.JRadioButton();
        rbCaixa = new javax.swing.JRadioButton();
        rbAtendente = new javax.swing.JRadioButton();
        pConfrmar = new br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu();
        lConfirmar = new javax.swing.JLabel();
        pConfrmar1 = new br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu();
        lCancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBorderGradient1.setFirstColor(new java.awt.Color(65, 38, 165));

        lTitulo1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo1.setText("Cadastro de Funcionario");

        panelBorderGradient2.setFirstColor(new java.awt.Color(255, 255, 255));
        panelBorderGradient2.setSecondColor(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nome");

        tfNome.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("CPF");

        tfCpf.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Login");

        tfLogin.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Senha");

        pfSenha.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email");

        tfEmail.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Telefone");

        tfTelefone.setBorder(null);

        panelBorderGradient3.setForeground(new java.awt.Color(255, 255, 255));
        panelBorderGradient3.setFirstColor(new java.awt.Color(204, 204, 204));
        panelBorderGradient3.setSecondColor(new java.awt.Color(255, 255, 255));

        panelBorderGradient4.setForeground(new java.awt.Color(255, 255, 255));
        panelBorderGradient4.setFirstColor(new java.awt.Color(255, 255, 255));
        panelBorderGradient4.setSecondColor(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tipo");

        buttonGroup1.add(rbGerente);
        rbGerente.setText("Gerente");

        buttonGroup1.add(rbCaixa);
        rbCaixa.setText("Caixa");

        buttonGroup1.add(rbAtendente);
        rbAtendente.setText("Atendente");

        javax.swing.GroupLayout panelBorderGradient4Layout = new javax.swing.GroupLayout(panelBorderGradient4);
        panelBorderGradient4.setLayout(panelBorderGradient4Layout);
        panelBorderGradient4Layout.setHorizontalGroup(
            panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorderGradient4Layout.createSequentialGroup()
                        .addComponent(rbGerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbAtendente)
                        .addGap(12, 12, 12)
                        .addComponent(rbCaixa))
                    .addComponent(jLabel5))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        panelBorderGradient4Layout.setVerticalGroup(
            panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbGerente)
                    .addComponent(rbAtendente)
                    .addComponent(rbCaixa))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBorderGradient3Layout = new javax.swing.GroupLayout(panelBorderGradient3);
        panelBorderGradient3.setLayout(panelBorderGradient3Layout);
        panelBorderGradient3Layout.setHorizontalGroup(
            panelBorderGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorderGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorderGradient3Layout.setVerticalGroup(
            panelBorderGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelBorderGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pConfrmar.setFirstColor(new java.awt.Color(65, 38, 165));
        pConfrmar.setSecondColor(new java.awt.Color(65, 38, 165));

        lConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        lConfirmar.setText("Confirmar");
        lConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lConfirmarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pConfrmarLayout = new javax.swing.GroupLayout(pConfrmar);
        pConfrmar.setLayout(pConfrmarLayout);
        pConfrmarLayout.setHorizontalGroup(
            pConfrmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfrmarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pConfrmarLayout.setVerticalGroup(
            pConfrmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfrmarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pConfrmar1.setFirstColor(new java.awt.Color(65, 38, 165));
        pConfrmar1.setSecondColor(new java.awt.Color(65, 38, 165));

        lCancelar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lCancelar.setText("Cancelar");
        lCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lCancelarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pConfrmar1Layout = new javax.swing.GroupLayout(pConfrmar1);
        pConfrmar1.setLayout(pConfrmar1Layout);
        pConfrmar1Layout.setHorizontalGroup(
            pConfrmar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfrmar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pConfrmar1Layout.setVerticalGroup(
            pConfrmar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfrmar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBorderGradient2Layout = new javax.swing.GroupLayout(panelBorderGradient2);
        panelBorderGradient2.setLayout(panelBorderGradient2Layout);
        panelBorderGradient2Layout.setHorizontalGroup(
            panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfEmail)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorderGradient2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addGap(248, 248, 248))
                        .addComponent(tfNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorderGradient2Layout.createSequentialGroup()
                            .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfTelefone)
                                .addComponent(jSeparator6)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorderGradient2Layout.createSequentialGroup()
                            .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jSeparator5)
                                .addComponent(pfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)))
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator4))
                    .addComponent(panelBorderGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradient2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pConfrmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pConfrmar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBorderGradient2Layout.setVerticalGroup(
            panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBorderGradient2Layout.createSequentialGroup()
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorderGradient2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBorderGradient2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBorderGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pConfrmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pConfrmar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBorderGradient1Layout = new javax.swing.GroupLayout(panelBorderGradient1);
        panelBorderGradient1.setLayout(panelBorderGradient1Layout);
        panelBorderGradient1Layout.setHorizontalGroup(
            panelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorderGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelBorderGradient1Layout.setVerticalGroup(
            panelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorderGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBorderGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBorderGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConfirmarMouseClicked

        if (tfNome.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Necessario colocar o nome");
            tfNome.requestFocus();

        } else if (tfLogin.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Necessario colocar o login");
            tfLogin.requestFocus();

        } else if (pfSenha.getPassword().equals(null)) {

            JOptionPane.showMessageDialog(null, "Necessario colocar a senha");
            pfSenha.requestFocus();

        } else if (tfEmail.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Necessario colocar o email");
            tfEmail.requestFocus();

        } else if (tfCpf.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Necessario colocar cpf");
            tfCpf.requestFocus();

        } else if (tfTelefone.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Necessario colocar o telefone");
            tfCpf.requestFocus();

        } else {

            if (rbAtendente.isSelected()) {

                
                funcionario.setNome(tfNome.getText());
                funcionario.setTipo(TipoFuncionario.Atendente);
                funcionario.setLogin(tfLogin.getText());
                funcionario.setSenha(String.valueOf(pfSenha.getPassword()));
                funcionario.setCpf(tfCpf.getText());
                funcionario.setStatusFuncionario(StatusFuncionario.Ativo);
                funcionario.setEmail(tfEmail.getText());
                funcionario.setTelefone(tfTelefone.getText());
                
                this.dispose();    
            } else if (rbCaixa.isSelected()) {

                funcionario.setNome(tfNome.getText());
                funcionario.setTipo(TipoFuncionario.Caixa);
                funcionario.setLogin(tfLogin.getText());
                funcionario.setSenha(String.valueOf(pfSenha.getPassword()));
                funcionario.setCpf(tfCpf.getText());
                funcionario.setStatusFuncionario(StatusFuncionario.Ativo);
                funcionario.setEmail(tfEmail.getText());
                funcionario.setTelefone(tfTelefone.getText());

                this.dispose();
                
            } else if (rbGerente.isSelected()) {

                funcionario.setNome(tfNome.getText());
                funcionario.setTipo(TipoFuncionario.Gerente);
                funcionario.setLogin(tfLogin.getText());
                funcionario.setSenha(String.valueOf(pfSenha.getPassword()));
                funcionario.setCpf(tfCpf.getText());
                funcionario.setStatusFuncionario(StatusFuncionario.Ativo);
                funcionario.setEmail(tfEmail.getText());
                funcionario.setTelefone(tfTelefone.getText());
                
                this.dispose();
                
            } else {

                JOptionPane.showMessageDialog(null, "Necessario colocar o tipo");
                rbGerente.requestFocus();
            }
        }
    }//GEN-LAST:event_lConfirmarMouseClicked

    private void lCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCancelarMouseClicked

        funcionario = null;

        this.dispose();
    }//GEN-LAST:event_lCancelarMouseClicked

    private void lCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCancelarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lCancelarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FuncionarioCreateForm dialog = new FuncionarioCreateForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lCancelar;
    private javax.swing.JLabel lConfirmar;
    private javax.swing.JLabel lTitulo1;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu pConfrmar;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu pConfrmar1;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradient panelBorderGradient1;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradient panelBorderGradient2;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradient panelBorderGradient3;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradient panelBorderGradient4;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JRadioButton rbAtendente;
    private javax.swing.JRadioButton rbCaixa;
    private javax.swing.JRadioButton rbGerente;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

}
