/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.model.Funcionario;
import br.edu.ifsp.pep.model.TipoFuncionario;
import br.ifsp.edu.pep.view.awt.PanelBorderGradient;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;

/**
 *
 * @author Abipeh
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalForm
     */
    private Point point = new Point();
    private static Funcionario funcionarioLogado;

    public static Funcionario getFuncionarioLogado() {

        return PrincipalForm.funcionarioLogado;
    }

    public PrincipalForm(Funcionario funcionario) {
        PanelBorderGradient teste = new PanelBorderGradient();
        this.funcionarioLogado = funcionario;

        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        verificarFuncionario();

        setBackground(new Color(0, 0, 0, 0));
        moveView();
    }

    private void moveView() {
        addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                if (!e.isMetaDown()) {
                    point.x = e.getX();
                    point.y = e.getY();
                }
            }
        });
        addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                if (!e.isMetaDown() && point.y <= 17) {
                    Point p = getLocation();
                    setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
                }
            }
        });
    }
    
    private void verificarFuncionario(){
        
        if(funcionarioLogado.getTipo() == TipoFuncionario.Caixa){
        
            lFuncionario.setVisible(false);
            lFornecedor.setVisible(false);
            lProduto.setVisible(false);
            lCompra.setVisible(false);
            lVenda.setVisible(false);
        }
        
        if(funcionarioLogado.getTipo() == TipoFuncionario.Atendente){
            
            lFuncionario.setVisible(false);
            lFornecedor.setVisible(false);
            lProduto.setVisible(false);
            lCaixa.setVisible(false);
            lCompra.setVisible(false);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelBorderGradient1 = new br.ifsp.edu.pep.view.awt.PanelBorderGradient();
        panelBorderGradient3 = new br.ifsp.edu.pep.view.awt.PanelBorderGradient();
        panelBorderGradient4 = new br.ifsp.edu.pep.view.awt.PanelBorderGradient();
        panelBorderGradient2 = new br.ifsp.edu.pep.view.awt.PanelBorderGradient();
        panelBorderGradient5 = new br.ifsp.edu.pep.view.awt.PanelBorderGradient();
        pesquisa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelBorderGradientButtonMenu2 = new br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu();
        lProduto = new javax.swing.JLabel();
        panelBorderGradientButtonMenu1 = new br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu();
        lFuncionario = new javax.swing.JLabel();
        panelBorderGradientButtonMenu5 = new br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu();
        lFornecedor = new javax.swing.JLabel();
        panelBorderGradientButtonMenu6 = new br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu();
        lCompra = new javax.swing.JLabel();
        panelBorderGradientButtonMenu9 = new br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu();
        lCaixa = new javax.swing.JLabel();
        panelBorderGradientButtonMenu8 = new br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu();
        lSair = new javax.swing.JLabel();
        lVenda = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout panelBorderGradient1Layout = new javax.swing.GroupLayout(panelBorderGradient1);
        panelBorderGradient1.setLayout(panelBorderGradient1Layout);
        panelBorderGradient1Layout.setHorizontalGroup(
            panelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelBorderGradient1Layout.setVerticalGroup(
            panelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelBorderGradient3.setFirstColor(new java.awt.Color(65, 38, 165));
        panelBorderGradient3.setFocusCycleRoot(true);
        panelBorderGradient3.setSecondColor(new java.awt.Color(65, 38, 165));

        panelBorderGradient4.setFirstColor(new java.awt.Color(255, 255, 255));
        panelBorderGradient4.setSecondColor(new java.awt.Color(255, 255, 255));

        panelBorderGradient2.setFirstColor(new java.awt.Color(65, 38, 165));
        panelBorderGradient2.setSecondColor(new java.awt.Color(65, 38, 165));

        panelBorderGradient5.setFirstColor(new java.awt.Color(255, 255, 255));
        panelBorderGradient5.setSecondColor(new java.awt.Color(255, 255, 255));

        pesquisa.setBorder(null);
        pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisaKeyPressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/pep/images/icons8-pesquisar-25.png"))); // NOI18N

        javax.swing.GroupLayout panelBorderGradient5Layout = new javax.swing.GroupLayout(panelBorderGradient5);
        panelBorderGradient5.setLayout(panelBorderGradient5Layout);
        panelBorderGradient5Layout.setHorizontalGroup(
            panelBorderGradient5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(22, 22, 22))
        );
        panelBorderGradient5Layout.setVerticalGroup(
            panelBorderGradient5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorderGradient5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBorderGradient2Layout = new javax.swing.GroupLayout(panelBorderGradient2);
        panelBorderGradient2.setLayout(panelBorderGradient2Layout);
        panelBorderGradient2Layout.setHorizontalGroup(
            panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradient2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelBorderGradient5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        panelBorderGradient2Layout.setVerticalGroup(
            panelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradient2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelBorderGradient5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Overcook");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/pep/images/branch-with-leaves (2).png"))); // NOI18N

        javax.swing.GroupLayout panelBorderGradient4Layout = new javax.swing.GroupLayout(panelBorderGradient4);
        panelBorderGradient4.setLayout(panelBorderGradient4Layout);
        panelBorderGradient4Layout.setHorizontalGroup(
            panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorderGradient2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorderGradient4Layout.createSequentialGroup()
                    .addGap(248, 248, 248)
                    .addGroup(panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBorderGradient4Layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jLabel5))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(248, Short.MAX_VALUE)))
        );
        panelBorderGradient4Layout.setVerticalGroup(
            panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradient4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorderGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
            .addGroup(panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorderGradient4Layout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addGroup(panelBorderGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(175, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Overcook");

        panelBorderGradientButtonMenu2.setFirstColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu2.setSecondColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu2MouseExited(evt);
            }
        });

        lProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/pep/images/icons8-adicionar-cesta-35.png"))); // NOI18N
        lProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lProdutoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBorderGradientButtonMenu2Layout = new javax.swing.GroupLayout(panelBorderGradientButtonMenu2);
        panelBorderGradientButtonMenu2.setLayout(panelBorderGradientButtonMenu2Layout);
        panelBorderGradientButtonMenu2Layout.setHorizontalGroup(
            panelBorderGradientButtonMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradientButtonMenu2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lProduto)
                .addContainerGap())
        );
        panelBorderGradientButtonMenu2Layout.setVerticalGroup(
            panelBorderGradientButtonMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradientButtonMenu2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lProduto)
                .addContainerGap())
        );

        panelBorderGradientButtonMenu1.setFirstColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu1.setSecondColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu1MouseExited(evt);
            }
        });

        lFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/pep/images/icons8-passe-de-segurança-35 (1).png"))); // NOI18N
        lFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lFuncionarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lFuncionarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBorderGradientButtonMenu1Layout = new javax.swing.GroupLayout(panelBorderGradientButtonMenu1);
        panelBorderGradientButtonMenu1.setLayout(panelBorderGradientButtonMenu1Layout);
        panelBorderGradientButtonMenu1Layout.setHorizontalGroup(
            panelBorderGradientButtonMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradientButtonMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorderGradientButtonMenu1Layout.setVerticalGroup(
            panelBorderGradientButtonMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradientButtonMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorderGradientButtonMenu5.setFirstColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu5.setSecondColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu5MouseExited(evt);
            }
        });

        lFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/pep/images/icons8-fornecedor-35.png"))); // NOI18N
        lFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lFornecedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lFornecedorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBorderGradientButtonMenu5Layout = new javax.swing.GroupLayout(panelBorderGradientButtonMenu5);
        panelBorderGradientButtonMenu5.setLayout(panelBorderGradientButtonMenu5Layout);
        panelBorderGradientButtonMenu5Layout.setHorizontalGroup(
            panelBorderGradientButtonMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradientButtonMenu5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFornecedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorderGradientButtonMenu5Layout.setVerticalGroup(
            panelBorderGradientButtonMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradientButtonMenu5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFornecedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorderGradientButtonMenu6.setFirstColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu6.setSecondColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu6MouseExited(evt);
            }
        });

        lCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/pep/images/icons8-carrinho-de-compras-35.png"))); // NOI18N
        lCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCompraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBorderGradientButtonMenu6Layout = new javax.swing.GroupLayout(panelBorderGradientButtonMenu6);
        panelBorderGradientButtonMenu6.setLayout(panelBorderGradientButtonMenu6Layout);
        panelBorderGradientButtonMenu6Layout.setHorizontalGroup(
            panelBorderGradientButtonMenu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradientButtonMenu6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lCompra)
                .addContainerGap())
        );
        panelBorderGradientButtonMenu6Layout.setVerticalGroup(
            panelBorderGradientButtonMenu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradientButtonMenu6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCompra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorderGradientButtonMenu9.setFirstColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu9.setSecondColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu9MouseExited(evt);
            }
        });

        lCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/pep/images/icons8-cash-register-35.png"))); // NOI18N
        lCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCaixaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBorderGradientButtonMenu9Layout = new javax.swing.GroupLayout(panelBorderGradientButtonMenu9);
        panelBorderGradientButtonMenu9.setLayout(panelBorderGradientButtonMenu9Layout);
        panelBorderGradientButtonMenu9Layout.setHorizontalGroup(
            panelBorderGradientButtonMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradientButtonMenu9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lCaixa)
                .addContainerGap())
        );
        panelBorderGradientButtonMenu9Layout.setVerticalGroup(
            panelBorderGradientButtonMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradientButtonMenu9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lCaixa)
                .addContainerGap())
        );

        panelBorderGradientButtonMenu8.setFirstColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu8.setSecondColor(new java.awt.Color(65, 38, 165));
        panelBorderGradientButtonMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBorderGradientButtonMenu8MouseExited(evt);
            }
        });

        lSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/pep/images/icons8-logout-35.png"))); // NOI18N
        lSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBorderGradientButtonMenu8Layout = new javax.swing.GroupLayout(panelBorderGradientButtonMenu8);
        panelBorderGradientButtonMenu8.setLayout(panelBorderGradientButtonMenu8Layout);
        panelBorderGradientButtonMenu8Layout.setHorizontalGroup(
            panelBorderGradientButtonMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradientButtonMenu8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorderGradientButtonMenu8Layout.setVerticalGroup(
            panelBorderGradientButtonMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradientButtonMenu8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lSair)
                .addContainerGap())
        );

        lVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/pep/images/icons8-vender-50.png"))); // NOI18N
        lVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lVendaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBorderGradient3Layout = new javax.swing.GroupLayout(panelBorderGradient3);
        panelBorderGradient3.setLayout(panelBorderGradient3Layout);
        panelBorderGradient3Layout.setHorizontalGroup(
            panelBorderGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderGradient3Layout.createSequentialGroup()
                .addGroup(panelBorderGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorderGradient3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorderGradient3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelBorderGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lVenda)
                            .addGroup(panelBorderGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelBorderGradientButtonMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelBorderGradientButtonMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelBorderGradientButtonMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelBorderGradientButtonMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelBorderGradientButtonMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelBorderGradientButtonMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorderGradient4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        panelBorderGradient3Layout.setVerticalGroup(
            panelBorderGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderGradient3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelBorderGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 6, Short.MAX_VALUE))
            .addGroup(panelBorderGradient3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(panelBorderGradientButtonMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBorderGradientButtonMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBorderGradientButtonMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBorderGradientButtonMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorderGradientButtonMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBorderGradientButtonMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderGradient3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderGradient3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelBorderGradientButtonMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu1MouseExited
        panelBorderGradientButtonMenu1.setFirstColor(Color.decode("#4325a7"));
        panelBorderGradientButtonMenu1.setSecondColor(Color.decode("#4325a7"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu1MouseExited

    private void panelBorderGradientButtonMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu1MouseEntered
        panelBorderGradientButtonMenu1.setFirstColor(Color.decode("#301c95"));
        panelBorderGradientButtonMenu1.setSecondColor(Color.decode("#301c95"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu1MouseEntered

    private void panelBorderGradientButtonMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu2MouseEntered
        panelBorderGradientButtonMenu2.setFirstColor(Color.decode("#301c95"));
        panelBorderGradientButtonMenu2.setSecondColor(Color.decode("#301c95"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu2MouseEntered

    private void panelBorderGradientButtonMenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu2MouseExited
        panelBorderGradientButtonMenu2.setFirstColor(Color.decode("#4325a7"));
        panelBorderGradientButtonMenu2.setSecondColor(Color.decode("#4325a7"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu2MouseExited

    private void panelBorderGradientButtonMenu5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu5MouseEntered
        panelBorderGradientButtonMenu5.setFirstColor(Color.decode("#301c95"));
        panelBorderGradientButtonMenu5.setSecondColor(Color.decode("#301c95"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu5MouseEntered

    private void panelBorderGradientButtonMenu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu5MouseExited
        panelBorderGradientButtonMenu5.setFirstColor(Color.decode("#4325a7"));
        panelBorderGradientButtonMenu5.setSecondColor(Color.decode("#4325a7"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu5MouseExited

    private void panelBorderGradientButtonMenu6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu6MouseEntered
        panelBorderGradientButtonMenu6.setFirstColor(Color.decode("#301c95"));
        panelBorderGradientButtonMenu6.setSecondColor(Color.decode("#301c95"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu6MouseEntered

    private void panelBorderGradientButtonMenu6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu6MouseExited
        panelBorderGradientButtonMenu6.setFirstColor(Color.decode("#4325a7"));
        panelBorderGradientButtonMenu6.setSecondColor(Color.decode("#4325a7"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu6MouseExited

    private void lFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFornecedorMouseClicked
        new FornecedorListForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_lFornecedorMouseClicked

    private void lFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFornecedorMouseEntered
        panelBorderGradientButtonMenu5.setFirstColor(Color.decode("#301c95"));
        panelBorderGradientButtonMenu5.setSecondColor(Color.decode("#301c95"));
    }//GEN-LAST:event_lFornecedorMouseEntered

    private void lFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFornecedorMouseExited
        panelBorderGradientButtonMenu5.setFirstColor(Color.decode("#4325a7"));
        panelBorderGradientButtonMenu5.setSecondColor(Color.decode("#4325a7"));
    }//GEN-LAST:event_lFornecedorMouseExited

    private void lFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFuncionarioMouseClicked
        new FuncionarioListForm(this, rootPaneCheckingEnabled).setVisible(true);

    }//GEN-LAST:event_lFuncionarioMouseClicked

    private void lFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFuncionarioMouseEntered
        panelBorderGradientButtonMenu1.setFirstColor(Color.decode("#301c95"));
        panelBorderGradientButtonMenu1.setSecondColor(Color.decode("#301c95"));
    }//GEN-LAST:event_lFuncionarioMouseEntered

    private void lFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFuncionarioMouseExited
        panelBorderGradientButtonMenu1.setFirstColor(Color.decode("#4325a7"));
        panelBorderGradientButtonMenu1.setSecondColor(Color.decode("#4325a7"));
    }//GEN-LAST:event_lFuncionarioMouseExited

    private void lProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProdutoMouseClicked
        new ProdutoListForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_lProdutoMouseClicked

    private void lProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProdutoMouseEntered
        panelBorderGradientButtonMenu2.setFirstColor(Color.decode("#301c95"));
        panelBorderGradientButtonMenu2.setSecondColor(Color.decode("#301c95"));
    }//GEN-LAST:event_lProdutoMouseEntered

    private void lProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProdutoMouseExited
        panelBorderGradientButtonMenu2.setFirstColor(Color.decode("#4325a7"));
        panelBorderGradientButtonMenu2.setSecondColor(Color.decode("#4325a7"));
    }//GEN-LAST:event_lProdutoMouseExited

    private void pesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = pesquisa.getText().toUpperCase();
            switch (texto) {
                case "Fornecedor":
                    new FornecedorCreateForm(this, rootPaneCheckingEnabled).setVisible(true);
                    break;
                case "Produto":
                    new ProdutoListForm(this, rootPaneCheckingEnabled).setVisible(true);
                    break;
                case "Caixa":
                    new CaixaForm(this, rootPaneCheckingEnabled).setVisible(true);
                    break;
                case "Funcionario":
                    new FuncionarioListForm(this, rootPaneCheckingEnabled).setVisible(true);
                    break;
                case "Compra":
                    new CompraForm(this, rootPaneCheckingEnabled).setVisible(true);
                    break;
            }
        }
    }//GEN-LAST:event_pesquisaKeyPressed

    private void lCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCompraMouseClicked
        
        new CompraForm(this, rootPaneCheckingEnabled).setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_lCompraMouseClicked

    private void lCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCaixaMouseClicked
        new CaixaForm(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_lCaixaMouseClicked

    private void panelBorderGradientButtonMenu8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelBorderGradientButtonMenu8MouseEntered

    private void panelBorderGradientButtonMenu8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelBorderGradientButtonMenu8MouseExited

    private void panelBorderGradientButtonMenu9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu9MouseEntered
        panelBorderGradientButtonMenu9.setFirstColor(Color.decode("#301c95"));
        panelBorderGradientButtonMenu9.setSecondColor(Color.decode("#301c95"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu9MouseEntered

    private void panelBorderGradientButtonMenu9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorderGradientButtonMenu9MouseExited
        panelBorderGradientButtonMenu9.setFirstColor(Color.decode("#4325a7"));
        panelBorderGradientButtonMenu9.setSecondColor(Color.decode("#4325a7"));
    }//GEN-LAST:event_panelBorderGradientButtonMenu9MouseExited

    private void lSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSairMouseClicked
        
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_lSairMouseClicked

    private void lVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lVendaMouseClicked
        
        new VendaForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_lVendaMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lCaixa;
    private javax.swing.JLabel lCompra;
    private javax.swing.JLabel lFornecedor;
    private javax.swing.JLabel lFuncionario;
    private javax.swing.JLabel lProduto;
    private javax.swing.JLabel lSair;
    private javax.swing.JLabel lVenda;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradient panelBorderGradient1;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradient panelBorderGradient2;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradient panelBorderGradient3;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradient panelBorderGradient4;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradient panelBorderGradient5;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu panelBorderGradientButtonMenu1;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu panelBorderGradientButtonMenu2;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu panelBorderGradientButtonMenu5;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu panelBorderGradientButtonMenu6;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu panelBorderGradientButtonMenu8;
    private br.ifsp.edu.pep.view.awt.PanelBorderGradientButtonMenu panelBorderGradientButtonMenu9;
    private javax.swing.JTextField pesquisa;
    // End of variables declaration//GEN-END:variables
}
