/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.dao.VendaDAO;
import br.edu.ifsp.pep.model.ItemPedido;
import br.edu.ifsp.pep.model.Produto;
import br.edu.ifsp.pep.model.Venda;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class VendaForm extends javax.swing.JDialog {
    
    
    private final List<ItemPedido> itemPedido = new ArrayList<>();
    private final Venda venda = new Venda();
    private Produto produtoSelecionado;


    /**
     * Creates new form VendaForm
     */
    public VendaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lProduto = new javax.swing.JLabel();
        sQuantidade = new javax.swing.JSpinner();
        lQuantidade = new javax.swing.JLabel();
        bConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduto = new javax.swing.JTable();
        bFinalizar = new javax.swing.JButton();
        bCancelarVenda = new javax.swing.JButton();
        bRemoverProduto = new javax.swing.JButton();
        bPesquisar = new javax.swing.JButton();
        tfProduto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(102, 102, 255));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Venda");

        lProduto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lProduto.setForeground(new java.awt.Color(102, 102, 255));
        lProduto.setText("Produto");

        sQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lQuantidade.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lQuantidade.setForeground(new java.awt.Color(102, 102, 255));
        lQuantidade.setText("Quantidade");

        bConfirmar.setBackground(new java.awt.Color(102, 102, 255));
        bConfirmar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        bConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        bConfirmar.setText("Confirmar");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        tableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Preço", "Preço Parcial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProduto);
        if (tableProduto.getColumnModel().getColumnCount() > 0) {
            tableProduto.getColumnModel().getColumn(0).setResizable(false);
            tableProduto.getColumnModel().getColumn(1).setResizable(false);
            tableProduto.getColumnModel().getColumn(2).setResizable(false);
            tableProduto.getColumnModel().getColumn(3).setResizable(false);
        }

        bFinalizar.setBackground(new java.awt.Color(102, 102, 255));
        bFinalizar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        bFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        bFinalizar.setText("Finalizar");
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarActionPerformed(evt);
            }
        });

        bCancelarVenda.setBackground(new java.awt.Color(255, 0, 0));
        bCancelarVenda.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        bCancelarVenda.setForeground(new java.awt.Color(255, 255, 255));
        bCancelarVenda.setText("Cancelar Venda");
        bCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarVendaActionPerformed(evt);
            }
        });

        bRemoverProduto.setBackground(new java.awt.Color(102, 102, 255));
        bRemoverProduto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        bRemoverProduto.setForeground(new java.awt.Color(255, 255, 255));
        bRemoverProduto.setText("Remover Produto");
        bRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverProdutoActionPerformed(evt);
            }
        });

        bPesquisar.setBackground(new java.awt.Color(102, 102, 255));
        bPesquisar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        bPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        bPesquisar.setText("Pesquisar");
        bPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisarActionPerformed(evt);
            }
        });

        tfProduto.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lProduto)
                            .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPesquisar)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lQuantidade)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bConfirmar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bRemoverProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bCancelarVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bFinalizar)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lTitulo)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lProduto)
                        .addGap(37, 37, 37)))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bRemoverProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisarActionPerformed
        ProdutoPesquisaForm produtoPesquisaForm = new ProdutoPesquisaForm(null, true);
        produtoPesquisaForm.setVisible(true);

        this.produtoSelecionado = produtoPesquisaForm.getProdutoSelecionado();
        if (this.produtoSelecionado != null)
        tfProduto.setText(this.produtoSelecionado.getDescricao());
        else
        tfProduto.setText("");
    }//GEN-LAST:event_bPesquisarActionPerformed

    private void bRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverProdutoActionPerformed
        int selectedRow = tableProduto.getSelectedRow();
        itemPedido.remove(selectedRow);

        this.atualizarTabela();
    }//GEN-LAST:event_bRemoverProdutoActionPerformed

    private void bCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarVendaActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarVendaActionPerformed

    private void bFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarActionPerformed
        venda.setItens(itemPedido);
        double valorTotal  = 0;
        for (ItemPedido ip : itemPedido) {
            valorTotal += ip.getPreco() * ip.getQuantidade();
        }
        venda.setTotalVenda(valorTotal);

        try {
            new VendaDAO().inserir(venda);
            JOptionPane.showMessageDialog(null, "Venda Registrada " + "\n"
                + "Senha do pedido: " + venda.getId());
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bFinalizarActionPerformed

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        if (this.produtoSelecionado == null) {
            JOptionPane.showMessageDialog(null,
                "Escolha um Produto.", "Alerta",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        Integer quantidade = Integer.valueOf(sQuantidade.getValue().toString());

        ItemPedido itemPedido = pesquisarItemPedido(produtoSelecionado);
        try {
            atualizaItemPedido(itemPedido, produtoSelecionado, quantidade);
            atualizarTabela();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                ex.getMessage(), "Alerta",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendaForm dialog = new VendaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarVenda;
    private javax.swing.JButton bConfirmar;
    private javax.swing.JButton bFinalizar;
    private javax.swing.JButton bPesquisar;
    private javax.swing.JButton bRemoverProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lProduto;
    private javax.swing.JLabel lQuantidade;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JSpinner sQuantidade;
    private javax.swing.JTable tableProduto;
    private javax.swing.JTextField tfProduto;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) tableProduto.getModel();
        model.setNumRows(0);
        for (ItemPedido ip : itemPedido) {

            model.addRow(new Object[]{ip.getProduto().getDescricao(),
                ip.getQuantidade(),
                ip.getPreco(),
                ip.getQuantidade() * ip.getPreco()
            });
        }
    }
    
    private ItemPedido pesquisarItemPedido(Produto produto) {
        for (ItemPedido ip : itemPedido) {
            if (ip.getProduto().equals(produto)) {
                return ip;
            }
        }
        return null;
    }

    private void atualizaItemPedido(ItemPedido itemPedido, Produto produto, Integer quantidade) throws Exception {
        if (itemPedido == null) {
            if (quantidade > produto.getQuantidade()) {
                throw new Exception("Quantidade Insuficiente em estoque.");
            }
            itemPedido = new ItemPedido(venda, produto, quantidade);
            this.itemPedido.add(itemPedido);
        } else {
            if (quantidade + itemPedido.getQuantidade() > produto.getQuantidade()) {
                throw new Exception("Quantidade Insuficiente em estoque.");
            }
            itemPedido.setQuantidade(quantidade + itemPedido.getQuantidade());
        }

    }


}
